# Generated by Django 5.0.6 on 2024-06-30 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvoScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=100)),
                ('custom_dialog_text', models.TextField()),
                ('stop_conversation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConvoOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('next_screen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from', to='convotemplates.convoscreen')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='convotemplates.convoscreen')),
            ],
        ),
        migrations.CreateModel(
            name='ConvoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initial_screen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_for', to='convotemplates.convoscreen')),
            ],
        ),
        migrations.AddField(
            model_name='convoscreen',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='convotemplates.convotemplate'),
        ),
    ]
