# Generated by Django 5.0.6 on 2024-06-30 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convotemplates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convotemplate',
            name='initial_screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initial_for', to='convotemplates.convoscreen'),
        ),
    ]
