# Generated by Django 5.0.6 on 2024-06-30 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convotemplates', '0002_alter_convotemplate_initial_screen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convooption',
            name='next_screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_options', to='convotemplates.convoscreen'),
        ),
        migrations.AlterField(
            model_name='convooption',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
