# Generated by Django 5.0.6 on 2024-07-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convotemplates', '0004_convooption_stf_reference_convoscreen_left_dialog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convooption',
            name='stf_reference',
        ),
        migrations.RemoveField(
            model_name='convoscreen',
            name='left_dialog',
        ),
        migrations.AddField(
            model_name='convooption',
            name='stfReference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='convoscreen',
            name='leftDialog',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='convoscreen',
            name='id_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='convotemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
